#include<bits/stdc++.h>
using namespace std;

/*
Problem Statement
Run-length Encoding is the string compression technique that compresses the given
string by replacing the number of consecutive identical characters (repeated 2 or more
times) with the concatenation of the character and its count of characters.
For Example:
If the given string is "wwwmpp", then, Run-length encoded string will
be "w3mp2",
Here, we replace 'www' with 'w3', as the frequency of 'w' is 3,
And, we replace 'pp' with 'p2', as the frequency of 'p' is 2,
Thus, the given string is compressed to "w3mp2",
Note, for 'm' we are not adding 1 because it is mentioned in the
definition of Run-Length Encoding, only 2 or more repeated character
count will be concatenated.
You are given a string 'Str' and an integer 'K'. Your task is to find the minimum possible
length of the run-length encoded string, which can be generated by deleting at most 'K'
characters from the string 'Str'.

*/



int minLengthOfCompressedString(string &str, int k) 
{
	// Write your code here


}